export const GLIDERS_LIST_LOADED_SUCCESS = 'GLIDERS_LIST_LOADED_SUCCESS';
export const GLIDERS_LIST_LOADED_FAILED = 'GLIDERS_LIST_LOADED_FAILED';
export const MANUFACTURER_LIST_LOADED_SUCCESS = 'MANUFACTURER_LIST_LOADED_SUCCESS';
export const MANUFACTURER_LIST_LOADED_FAILED = 'MANUFACTURER_LIST_LOADED_FAILED';
export const GLIDER_SAVE_SUCCESS = 'GLIDER_SAVE_SUCCESS';
export const GLIDER_SAVE_FAILED = 'GLIDER_SAVE_FAILED';